<a href="https://colab.research.google.com/github/zoboro/Python-101/blob/main/8_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas
Pandas is a Python library used for data manipulation, cleaning, analysis, and handling tabular data.

It uses two data structures to store data:
1.   Series - 1-D array with data labels called index
2.   Dataframe - 2-D, mutable table with labeled axes (rows and columns)

##Import

In [105]:
from huggingface_hub import whoami
from google.colab import userdata

from huggingface_hub import login
login(userdata.get("Data-jobs"))

print(whoami())

{'type': 'user', 'id': '6a3a9fa8cef61aeacd7e6cda', 'name': 'zoboro', 'fullname': 'Dipanshu Khandelwal', 'isPro': False, 'avatarUrl': '/avatars/3ff11c2ba62d478ed6bf471763811a9a.svg', 'orgs': [], 'auth': {'type': 'access_token', 'accessToken': {'displayName': 'Data-jobs', 'role': 'fineGrained', 'createdAt': '2026-06-23T15:04:23.055Z', 'fineGrained': {'canReadGatedRepos': True, 'global': [], 'scoped': [{'entity': {'_id': '6a3a9fa8cef61aeacd7e6cda', 'type': 'user', 'name': 'zoboro'}, 'permissions': ['repo.content.read', 'repo.access.read']}]}}}}

In [106]:
from datasets import load_dataset

# Loading Data
import pandas as pd

df = pd.read_csv("hf://datasets/lukebarousse/data_jobs/data_jobs.csv")

##Load Data

In [107]:
# pd.read_csv('path_to_file.csv')
# pd.read_excel('path_to_file.xlsx')

In [108]:
# Loading Data
import pandas as pd

df = pd.read_csv("hf://datasets/lukebarousse/data_jobs/data_jobs.csv")

##Dataframes
A DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.

###Rows and Columns
DataFrames consist of rows and columns, where each row represents a single observation or record, and each column represents a variable or feature.

In [109]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

###Columns

In [110]:
df['job_title_short']

0         Senior Data Engineer
1                 Data Analyst
2                Data Engineer
3                Data Engineer
4                Data Engineer
                  ...
785736       Software Engineer
785737            Data Analyst
785738        Business Analyst
785739           Data Engineer
785740       Software Engineer
Name: job_title_short, Length: 785741, dtype: object

In [111]:
df.job_title_short

0         Senior Data Engineer
1                 Data Analyst
2                Data Engineer
3                Data Engineer
4                Data Engineer
                  ...
785736       Software Engineer
785737            Data Analyst
785738        Business Analyst
785739           Data Engineer
785740       Software Engineer
Name: job_title_short, Length: 785741, dtype: object

###Index

In [112]:
df.job_title_short[785740]

'Software Engineer'

##View

In [113]:
##Head
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [114]:
##Tail
df.tail()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [115]:
##Shape
print(df.shape)

(785741, 17)

##Get Info
To get a concise summary for the DataFrame we'll be using `df.info`.

* Total number of entries
* Number of columns
* Column name
* Count of non-null items in each column
* Data type of each column

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [117]:
df.dtypes

job_title_short           object
job_title                 object
job_location              object
job_via                   object
job_schedule_type         object
job_work_from_home          bool
search_location           object
job_posted_date           object
job_no_degree_mention       bool
job_health_insurance        bool
job_country               object
salary_rate               object
salary_year_avg          float64
salary_hour_avg          float64
company_name              object
job_skills                object
job_type_skills           object
dtype: object

In [118]:
df['job_title_short'].unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

##Accessing Data

###Variables (Columns)

In [119]:
df.job_title

0         Senior Clinical Data Engineer / Principal Clin...
1                                              Data Analyst
2         Data Engineer/Scientist/Analyst, Mid or Senior...
3         LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...
4                                    Data Engineer- Sr Jobs
                                ...
785736                                      DevOps Engineer
785737                                     CRM Data Analyst
785738                       Commercial Analyst - Start Now
785739    Principal Associate, Data Engineer (Remote-Eli...
785740                                   AWS System Analyst
Name: job_title, Length: 785741, dtype: object

In [120]:
df[['job_title','job_location']]

,job_title,job_location
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT"
1,Data Analyst,"Guadalajara, Jalisco, Mexico"
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany"
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX"
4,Data Engineer- Sr Jobs,"Washington, DC"
...,...,...
785736,DevOps Engineer,Singapura
785737,CRM Data Analyst,"Bad Rodach, Jerman"
785738,Commercial Analyst - Start Now,Malaysia
785739,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat"
785740,AWS System Analyst,India

###Observations (Rows)

In [121]:
df.iloc[1]

job_title_short                                               Data Analyst
job_title                                                     Data Analyst
job_location                                  Guadalajara, Jalisco, Mexico
job_via                                                   via BeBee México
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Mexico
job_posted_date                                        2023-01-14 13:18:07
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                         Mexico
salary_rate                                                            NaN
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                                    Hewlett Packard Enterprise
job_skills               ['r', 'python', 'sql', 'nosql', 'power bi', 't...
job_type_skills          {'analyst_tools': ['power bi', 'tableau'], 'pr...
Name: 1, dtype: object

In [122]:
df.iloc[2:5]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

####Filtering Rows

In [123]:
df[df['salary_year_avg'] > 100000]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
116,Data Scientist,Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-10-04 13:04:23,False,False,United States,year,114000.0,NaN,4 Corner Resources,"['r', 'python', 'sql', 't-sql', 'hadoop', 'spa...","{'analyst_tools': ['tableau'], 'libraries': ['..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",NaN,NaN
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [124]:
df[df['job_title_short'] == 'Senior Data Engineer']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
13,Senior Data Engineer,Senior Data Engineer,"New York, NY",via LinkedIn,Full-time,False,"Texas, United States",2023-11-15 13:08:52,True,True,United States,NaN,NaN,NaN,Nayya,"['python', 'sql', 'go', 'ruby', 'ruby', 'javas...","{'cloud': ['aws'], 'other': ['terraform'], 'pr..."
30,Senior Data Engineer,Senior Data Engineer (Work from home Eligible),"Wilmington, DE",via WDHN Jobs,Full-time,False,"Texas, United States",2023-03-29 13:32:03,False,True,United States,NaN,NaN,NaN,Capital One,"['scala', 'python', 'nosql', 'mongo', 'shell',...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."
42,Senior Data Engineer,"Senior Data Engineer(Python)-1563,1637&1633","Chennai, Tamil Nadu, India",via HR Software For Growing Businesses | Fresh...,Full-time,False,India,2023-11-10 13:30:41,True,False,India,NaN,NaN,NaN,CESIT,"['python', 'sql', 'aws', 'pyspark', 'docker', ...","{'async': ['jira'], 'cloud': ['aws'], 'librari..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785709,Senior Data Engineer,Senior Data Engineer,"Berlin, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,False,False,Germany,NaN,NaN,NaN,Cherry Ventures,"['sql', 'hadoop', 'spark']","{'libraries': ['hadoop', 'spark'], 'programmin..."
785710,Senior Data Engineer,(Senior) Data Engineer (m/w/d) - PUBLIC BW / C...,"Leinfelden-Echterdingen, Jerman",melalui Monster.de,Pekerjaan tetap,False,Germany,2023-03-13 06:18:59,False,False,Germany,NaN,NaN,NaN,"CGI Group, Inc.","['python', 'sql', 'azure', 'aws', 'hadoop', 's...","{'cloud': ['azure', 'aws'], 'libraries': ['had..."
785711,Senior Data Engineer,Senior Data Engineer (m/w/d),"Düsseldorf, Jerman",melalui Monster.de,Pekerjaan tetap,False,Germany,2023-03-13 06:18:59,False,False,Germany,NaN,NaN,NaN,"CGI Group, Inc.","['gcp', 'aws', 'azure', 'spark', 'hadoop']","{'cloud': ['gcp', 'aws', 'azure'], 'libraries'..."
785719,Senior Data Engineer,Senior Data Engineer für Data Lakehouse (m/w/d),"Karlsruhe, Jerman",melalui KHON2 Jobs,Pekerjaan tetap,False,Germany,2023-03-13 06:18:59,False,False,Germany,NaN,NaN,NaN,Workwise GmbH,"['python', 'scala', 'kafka', 'flow']","{'libraries': ['kafka'], 'other': ['flow'], 'p..."
785735,Senior Data Engineer,Senior Data Engineer,"Berlin, Jerman",melalui Top County Careers,Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,False,False,Germany,NaN,NaN,NaN,Pure App,"['sql', 'python', 'bigquery', 'aws', 'airflow'...","{'cloud': ['bigquery', 'aws'], 'libraries': ['..."

##NA Values
`pd.notna()` displays if the values are not NA
* Non missing values are `True`
* Missing values are `False`

In [125]:
df[df['salary_year_avg'].notna()]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",NaN,NaN
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [126]:
df[df[['salary_year_avg', 'job_skills']].notna().all(axis=1)]

# #all(axis=1) returns the values where for each row, are all selected
# conditions True %%

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785563,Data Scientist,Data Scientist I/II (Model Risk Management & M...,"Pensacola, FL",via Navy Federal Credit Union - Talentify,Full-time,False,"Florida, United States",2023-01-11 06:22:10,False,False,United States,year,136400.0,NaN,Navy Federal Credit Union,"['r', 'python', 'matplotlib', 'ggplot2', 'spar...","{'analyst_tools': ['word', 'power bi', 'tablea..."
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [127]:
##Returns boolean values for each index
df.notna()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,False,False
1,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785737,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785738,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785739,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785740,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True

##Date and Time

In [128]:
##DateTime
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

##Extract Year
df['year'] = df['job_posted_date'].dt.year

##Extract Month
df['month'] = df['job_posted_date'].dt.month

##Extract Day
df['day'] = df['job_posted_date'].dt.day

##Extract Date
df['date'] = df['job_posted_date'].dt.date

df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,...,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,year,month,day,date
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,...,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN,2023,6,16,2023-06-16
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,...,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr...",2023,1,14,2023-01-14
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,...,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",2023,10,10,2023-10-10
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,...,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",2023,7,4,2023-07-04
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,...,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...",2023,8,7,2023-08-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,...,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete...",2023,3,13,2023-03-13
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,...,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi...",2023,3,12,2023-03-12
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,...,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}",2023,3,12,2023-03-12
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,...,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh...",2023,3,12,2023-03-12
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,...,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}",2023,3,13,2023-03-13

##Sorting Values
`sort_values()` sorts a DataFrame or a specific column in ascending or descending order based on one or more columns.
Parameters:
* `by` - column name or list of column names to sort by
* `ascending` - boolean or list of booleans, default True, to sort by descending you would use False
* `inplace` - whether to modify the DataFrame in place or return a new one

In [129]:
##Sort DataFrame by the job_posted_date in descending order

df.sort_values(by='job_posted_date', ascending=False, inplace=True)
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,...,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,year,month,day,date
90102,Machine Learning Engineer,Intelligence analyst,"Boston, MA",via Talent.com,Full-time,False,"New York, United States",2023-12-31 23:59:58,True,False,...,NaN,NaN,NaN,VirtualVocations,NaN,NaN,2023,12,31,2023-12-31
112373,Senior Data Analyst,Marketing Data & Analytics Product Owner - Sen...,"Boston, MA (+1 other)",via Boston Consulting Group,Full-time,False,"New York, United States",2023-12-31 23:59:58,False,False,...,NaN,NaN,NaN,Boston Consulting Group,"['sql', 'python', 'r', 'gdpr', 'tableau', 'pow...","{'analyst_tools': ['tableau', 'power bi'], 'li...",2023,12,31,2023-12-31
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,...,year,140000.0,NaN,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",2023,12,31,2023-12-31
362129,Data Engineer,Data engineer,"Sunnyvale, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,True,False,...,NaN,NaN,NaN,ITCO Solutions,"['sql', 'python', 'java', 'snowflake', 'airflo...","{'cloud': ['snowflake'], 'libraries': ['airflo...",2023,12,31,2023-12-31
351830,Data Engineer,Data engineer,"San Francisco, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,False,False,...,NaN,NaN,NaN,JBL Resources,"['azure', 'power bi', 'word']","{'analyst_tools': ['power bi', 'word'], 'cloud...",2023,12,31,2023-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72158,Senior Data Analyst,Senior Data Analyst / Platform Experience,"Worcester, MA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01 00:00:27,False,True,...,NaN,NaN,NaN,Atria Wealth Solutions,"['sql', 'atlassian', 'jira']","{'async': ['jira'], 'other': ['atlassian'], 'p...",2023,1,1,2023-01-01
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,...,NaN,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}",2023,1,1,2023-01-01
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,...,NaN,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud...",2023,1,1,2023-01-01
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,...,NaN,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq...",2023,1,1,2023-01-01
108804,Data Analyst,Data Analyst,"New York, NY",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:04,False,False,...,NaN,NaN,NaN,Metasys Technologies,"['sql', 'snowflake', 'visio', 'jira', 'conflue...","{'analyst_tools': ['visio'], 'async': ['jira',...",2023,1,1,2023-01-01

##Adding Column
If you want to create a column you'll need to use the `df['column_name']` syntax.

In [130]:
##If the column job_title_short is equal to 'Data Analyst' then then return 1 if not, return 0. It does this by using astype(int).
df['Is Data Analyst'] = (df.job_title_short == 'Data Analyst').astype(int)
df['Is Data Analyst']

90102     0
112373    0
327439    0
362129    0
351830    0
         ..
72158     0
110290    1
98438     1
96906     1
108804    1
Name: Is Data Analyst, Length: 785741, dtype: int64

In [131]:
df[df['Is Data Analyst'] > 0]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,...,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,year,month,day,date,Is Data Analyst
358496,Data Analyst,Data analyst,"Hobbs, NM",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:10,True,False,...,NaN,NaN,FlexJobs,NaN,NaN,2023,12,31,2023-12-31,1
356798,Data Analyst,Data analyst,"Gilbert, AZ",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:10,True,False,...,NaN,NaN,FlexJobs,NaN,NaN,2023,12,31,2023-12-31,1
326336,Data Analyst,Data analyst,"Topeka, KS",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:07,True,False,...,NaN,NaN,FlexJobs,NaN,NaN,2023,12,31,2023-12-31,1
358704,Data Analyst,Data analyst,"Chandler, AZ",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:07,True,False,...,NaN,NaN,FlexJobs,NaN,NaN,2023,12,31,2023-12-31,1
349026,Data Analyst,Data internship,"Dallas, TX",via Talent.com,Full-time and Internship,False,Sudan,2023-12-31 23:40:03,False,False,...,NaN,NaN,Paramount Global,NaN,NaN,2023,12,31,2023-12-31,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104526,Data Analyst,Jr. Data Analyst,"Torrance, CA",via Recruit.net,Full-time,False,"California, United States",2023-01-01 00:00:38,False,False,...,NaN,NaN,Aquent,['excel'],{'analyst_tools': ['excel']},2023,1,1,2023-01-01,1
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,...,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}",2023,1,1,2023-01-01,1
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,...,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud...",2023,1,1,2023-01-01,1
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,...,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq...",2023,1,1,2023-01-01,1
108804,Data Analyst,Data Analyst,"New York, NY",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:04,False,False,...,NaN,NaN,Metasys Technologies,"['sql', 'snowflake', 'visio', 'jira', 'conflue...","{'analyst_tools': ['visio'], 'async': ['jira',...",2023,1,1,2023-01-01,1

##Dropping Data
Use `drop()` if you want to drop (delete) either a column or row in your database.

The syntax is:
* Drop column: `df.drop('column_name, axis = 1)`
* Drop row: `df.drop(index_name, axis = 0)`

If you wanted to drop multiple rows you would have the syntax:
* Drop multiple columns: `df.drop(['column_name1', 'column_name2'], axis=1)`
* Drop multiple rows: `df.drop([index_name1, index_name2], axis=0)`

In [132]:
df.drop(['year','month','day','date'], axis = 1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 90102 to 108804
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  Is Data Analyst        785741 non-null  int64
dtypes: bool(3), datetime64[ns](1), float64(2), int64(1), object(11)
memory usage: 98.2+ MB

##Remove NA
To remove rows that contain empty cells use `dropna()`.

In [133]:
df.salary_year_avg.head()

90102          NaN
112373         NaN
327439    140000.0
362129         NaN
351830         NaN
Name: salary_year_avg, dtype: float64

In [134]:
##Cleanup salary_year_avg column by removing the NaN values

df.dropna(subset=['salary_year_avg'])
df.salary_year_avg.head()

90102          NaN
112373         NaN
327439    140000.0
362129         NaN
351830         NaN
Name: salary_year_avg, dtype: float64

##Descriptive Statistics

###Describe()
It gets the following (for columns with numeric data):
* count, mean, std, min, max and quartile data

In [135]:
df.describe(include='all')

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,Is Data Analyst
count,785741,785740,784696,785733,773074,785741,785741,785741,785741,785741,785692,33067,22003.000000,10662.000000,785723,668704,668704,785741.000000
unique,10,234673,17217,7903,47,2,173,NaN,2,2,160,5,NaN,NaN,139982,177562,177562,NaN
top,Data Analyst,Data Engineer,Anywhere,via LinkedIn,Full-time,False,India,NaN,False,False,United States,year,NaN,NaN,Emprego,['excel'],{'analyst_tools': ['excel']},NaN
freq,196075,53908,69552,186679,701727,716189,51088,NaN,544965,699244,206292,22004,NaN,NaN,6664,13238,13238,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-06-25 16:02:11.860247296,NaN,NaN,NaN,NaN,123286.274072,47.016598,NaN,NaN,NaN,0.249542
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-01-01 00:00:04,NaN,NaN,NaN,NaN,15000.000000,8.000000,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-03-20 10:05:48,NaN,NaN,NaN,NaN,90000.000000,27.500000,NaN,NaN,NaN,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-06-29 06:11:38,NaN,NaN,NaN,NaN,115000.000000,45.980000,NaN,NaN,NaN,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-27 01:01:16,NaN,NaN,NaN,NaN,150000.000000,61.159996,NaN,NaN,NaN,0.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-31 23:59:58,NaN,NaN,NaN,NaN,960000.000000,391.000000,NaN,NaN,NaN,1.000000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48312.449482,21.890738,NaN,NaN,NaN,0.432748

###Common Data Analysis Methods
* `df.sum()` - Sum of values
* `df.cumsum()` - Cummulative sum of values
* `df.min()/df.max()` - Minimum/maximum values
* `df.idxmin()/df.idxmax()` - Indexes of minimum/Maximum value
* `df.mean()` - Mean of values
* `df.median()` - Median of values
* `df.mode()` - Mode of the values
* `df.nunique()` — Number of distinct (non-NA) values per column
* `series.value_counts()` - Counts of unique values for a Series (aka a column)
  * Typically used for counting unique occurrences within a single column.
  * It's not applicable to an entire DataFrame without specifying a column.
* Depending on the method, you can apply it directly to a DataFrame or a Series.

In [136]:
df.count()

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
Is Data Analyst          785741
dtype: int64

In [137]:
df['salary_year_avg'].median()

115000.0

In [138]:
df['salary_year_avg'].idxmax()

np.int64(554784)

In [139]:
df.loc[df['salary_year_avg'].idxmax()]

job_title_short                                           Data Scientist
job_title                                                 Data Scientist
job_location                                                 Madison, SD
job_via                                    via Cooperative Career Center
job_schedule_type                                              Full-time
job_work_from_home                                                 False
search_location                                  Illinois, United States
job_posted_date                                      2023-05-04 19:06:06
job_no_degree_mention                                              False
job_health_insurance                                                True
job_country                                                United States
salary_rate                                                         year
salary_year_avg                                                 960000.0
salary_hour_avg                                                      NaN
company_name                 East River Electric Power Cooperative, Inc.
job_skills                                ['java', 'c++', 'python', 'r']
job_type_skills          {'programming': ['java', 'c++', 'python', 'r']}
Is Data Analyst                                                        0
Name: 554784, dtype: object

In [140]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

##Aggregation

###Groupby()
* Use groupby to group your DataFrame by the unique values in a specific column.
* Lets you perform aggregation (e.g. mean, sum) on the grouped data.
* Aggregations that can be performed:
`mean()`, `median()`, `sum()`, `min()`, `max()`, `count()`, `size()`, `first()`, `last()`, `unique()`, etc.

In [141]:
df.groupby('job_title_short')['salary_year_avg'].mean()

job_title_short
Business Analyst              91082.612833
Cloud Engineer               111268.453846
Data Analyst                  93841.907854
Data Engineer                130125.604250
Data Scientist               135988.837171
Machine Learning Engineer    126774.315972
Senior Data Analyst          113911.363665
Senior Data Engineer         145840.611624
Senior Data Scientist        154206.292996
Software Engineer            113393.760054
Name: salary_year_avg, dtype: float64

In [142]:
df.groupby('job_title_short')['salary_year_avg'].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

###Agg()
`agg()` lets you apply multiple functions at once.

In [143]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min', 'max'])

                               min       max
job_title_short
Business Analyst           16500.0  387460.0
Cloud Engineer             42000.0  280000.0
Data Analyst               25000.0  650000.0
Data Engineer              15000.0  525000.0
Data Scientist             27000.0  960000.0
Machine Learning Engineer  30000.0  325000.0
Senior Data Analyst        30000.0  425000.0
Senior Data Engineer       35000.0  425000.0
Senior Data Scientist      45000.0  890000.0
Software Engineer          28000.0  375000.0